language: python

python:
  - "3.6"
  - "2.7"

env:
  R_LIBS=$HOME/R_libs/

cache:
  directories:
    - $HOME/R_libs
    - $HOME/.cache/pip

before_install:
  - sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty-cran35/" >> /etc/apt/sources.list'
  - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
  - gpg -a --export E084DAB9 | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -y install r-base
  - R -e "if (!requireNamespace('BiocManager', quietly = TRUE)){install.packages('BiocManager', repos='https://CRAN.R-project.org')}; BiocManager::install(c('sva', 'bladderbatch'), version = '3.8')"

install:
  - pip install -r requirements.txt
  - pip install -r requirements.test.txt

script:
  - pytest --disable-warnings tests/test_*.py
